#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGFile
@end

@interface SWGFile : SWGObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* url;

@end
