#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGImage.h"


@protocol SWGFileResult
@end

@interface SWGFileResult : SWGObject


@property(nonatomic) NSArray<SWGImage>* price;

@end
