#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGImageSizeVm.h"


@protocol SWGImageValidationVm
@end

@interface SWGImageValidationVm : SWGObject


@property(nonatomic) NSString* sku;

@property(nonatomic) NSArray<SWGImageSizeVm>* images;

@end
