#import <Foundation/Foundation.h>
#import "SWGFileResult.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGImagesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGImagesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGImagesApi*) sharedAPI;
///
///
/// POSTs files to a temporary store
/// POSTs files to a temporary store
///
/// @param images Form/multipart file post
/// 
///
/// @return SWGFileResult*
-(NSNumber*) postImagesWithImages: (NSURL*) images
    completionHandler: (void (^)(SWGFileResult* output, NSError* error)) handler;



@end
