#import <Foundation/Foundation.h>
#import "SWGImageValidationVm.h"
#import "SWGImageValidatorResult.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGImagevalidationApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGImagevalidationApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGImagevalidationApi*) sharedAPI;
///
///
/// Submit image validation
/// Validates an images and returns a validation errors (if available).
///
/// @param req Image validation request, contains sku and image sizes per space
/// 
///
/// @return SWGImageValidatorResult*
-(NSNumber*) pOSTImagevalidationWithReq: (SWGImageValidationVm*) req
    completionHandler: (void (^)(SWGImageValidatorResult* output, NSError* error)) handler;



@end
