#import <Foundation/Foundation.h>
#import "SWGLanguageDictionary.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGLanguagesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGLanguagesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGLanguagesApi*) sharedAPI;
///
///
/// Get text in a specified language
/// Get text in a specified language
///
/// @param languageCode Two-character language code, like \&quot;en\&quot; (english)
/// @param key A string used to query the language dictionary for specific values within a category.
/// 
///
/// @return SWGLanguageDictionary*
-(NSNumber*) getLanguageTextWithLanguageCode: (NSString*) languageCode
    key: (NSString*) key
    completionHandler: (void (^)(SWGLanguageDictionary* output, NSError* error)) handler;



@end
