#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGKeyValuePair.h"


@protocol SWGLanguageDictionary
@end

@interface SWGLanguageDictionary : SWGObject


@property(nonatomic) NSString* category;

@property(nonatomic) NSArray<SWGKeyValuePair>* values;

@end
