#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGOrderItem.h"
#import "SWGPayment.h"
#import "SWGShipToAddress.h"


@protocol SWGOrder
@end

@interface SWGOrder : SWGObject


@property(nonatomic) SWGShipToAddress* shipToAddress;

@property(nonatomic) NSArray<SWGOrderItem>* items;

@property(nonatomic) SWGPayment* payment;

@property(nonatomic) NSString* couponCode;

@end
