#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGPriceInfo.h"


@protocol SWGOrderPriceResult
@end

@interface SWGOrderPriceResult : SWGObject


@property(nonatomic) SWGPriceInfo* items;

@property(nonatomic) SWGPriceInfo* shipping;

@property(nonatomic) SWGPriceInfo* tax;

@property(nonatomic) SWGPriceInfo* couponCode;

@property(nonatomic) NSString* couponType;

@property(nonatomic) NSString* couponUsed;

@property(nonatomic) NSNumber* hadCouponApply;

@property(nonatomic) NSNumber* dollarsOff;

@property(nonatomic) NSNumber* percentOff;

@property(nonatomic) NSNumber* hadError;

@end
