#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGOrderItemImage.h"


@protocol SWGOrderItem
@end

@interface SWGOrderItem : SWGObject


@property(nonatomic) NSNumber* quantity;

@property(nonatomic) NSString* sKU;

@property(nonatomic) NSNumber* shipCarrierMethodId;

@property(nonatomic) NSArray<SWGOrderItemImage>* images;

@end
