#import <Foundation/Foundation.h>
#import "SWGOrderStatusUpdateResult.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGOrderstatusApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGOrderstatusApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGOrderstatusApi*) sharedAPI;
///
///
/// Update an order status
/// Update status of each order item.
///
/// @param _id Order Id
/// @param orderStatusName Order status name for update
/// 
///
/// @return SWGOrderStatusUpdateResult*
-(NSNumber*) pOSTOrderstatusWithId: (NSString*) _id
    orderStatusName: (NSString*) orderStatusName
    completionHandler: (void (^)(SWGOrderStatusUpdateResult* output, NSError* error)) handler;



@end
