#import <Foundation/Foundation.h>
#import "SWGPostSubmittedOrder.h"
#import "SWGPostOrder.h"
#import "SWGOrderResult.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGOrdersApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGOrdersApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGOrdersApi*) sharedAPI;
///
///
/// Get an order
/// Gets basic information about an order.
///
/// @param _id Order Id
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// @param languageCode Resultant info language. Defaults to &#39;en&#39;.
/// 
///
/// @return SWGPostSubmittedOrder*
-(NSNumber*) gETOrdersWithId: (NSString*) _id
    version: (NSNumber*) version
    source: (NSString*) source
    languageCode: (NSString*) languageCode
    completionHandler: (void (^)(SWGPostSubmittedOrder* output, NSError* error)) handler;


///
///
/// Submit an order
/// Places an order into the system. An order can be submitted as PrePayment (in order to temporarily place an order and get an ID for Paypal) using the IsPreSubmit flag.
///
/// @param order Order to be submitted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return SWGOrderResult*
-(NSNumber*) pOSTOrdersWithOrder: (SWGPostOrder*) order
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(SWGOrderResult* output, NSError* error)) handler;



@end
