#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProductPreviewResponse
@end

@interface SWGProductPreviewResponse : SWGObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSNumber* hadError;

@property(nonatomic) NSString* errorMessage;

@end
