#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMeta.h"
#import "SWGOrderPayment.h"
#import "SWGPostOrderItem.h"
#import "SWGShipToAddress.h"


@protocol SWGPostOrder
@end

@interface SWGPostOrder : SWGObject


@property(nonatomic) SWGShipToAddress* shipToAddress;

@property(nonatomic) SWGShipToAddress* billingAddress;

@property(nonatomic) NSArray<SWGPostOrderItem>* items;

@property(nonatomic) SWGOrderPayment* payment;
/* Clients can submit an ID they use for the order here. 
 */
@property(nonatomic) NSString* sourceId;
/* Submit the order into PrePayment status. 
 */
@property(nonatomic) NSNumber* isPreSubmit;

@property(nonatomic) NSString* couponCode;
/* An optional Map<string,string> of misc properties. 
 */
@property(nonatomic) SWGMeta* meta;

@end
