#import <Foundation/Foundation.h>
#import "SWGProductList.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGProductsApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGProductsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGProductsApi*) sharedAPI;
///
///
/// Get a list of products
/// Get a list of products. The products returned may have variants. Products returned are only those within the overall recipe. All images returned from the service are dynamically resizable by adding width and height querystrings.
///
/// @param countryCode The country code where it would be shipped to. For example, &#39;US&#39; or &#39;CA&#39;
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// @param all Whether or not to return all available printio products, or just ones in your recipe. Pass &#39;true&#39; or &#39;false&#39;.
/// @param languageCode Two-character language code, defaults to \&quot;en\&quot; (english)
/// @param currencyCode Three character currency code, defaults to \&quot;USD\&quot; (united states dollar)
/// 
///
/// @return SWGProductList*
-(NSNumber*) getProductsWithCountryCode: (NSString*) countryCode
    version: (NSNumber*) version
    source: (NSString*) source
    all: (NSString*) all
    languageCode: (NSString*) languageCode
    currencyCode: (NSString*) currencyCode
    completionHandler: (void (^)(SWGProductList* output, NSError* error)) handler;



@end
