#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMeta.h"
#import "SWGPostSubmittedItem.h"
#import "SWGProductPriceInfo.h"
#import "SWGShipToAddress.h"


@protocol SWGPostSubmittedOrder
@end

@interface SWGPostSubmittedOrder : SWGObject

/* The unique ID we use within our system. 
 */
@property(nonatomic) NSString* _id;
/* A short, non-unique ID that is optionally used for customer service. 
 */
@property(nonatomic) NSString* niceId;
/* Partner's internal ID-- entirely optional 
 */
@property(nonatomic) NSString* souceId;

@property(nonatomic) NSArray<SWGPostSubmittedItem>* items;

@property(nonatomic) SWGProductPriceInfo* total;

@property(nonatomic) SWGProductPriceInfo* shippingTotal;

@property(nonatomic) SWGProductPriceInfo* discountAmount;

@property(nonatomic) NSString* discountCode;

@property(nonatomic) SWGShipToAddress* billingAddress;

@property(nonatomic) SWGShipToAddress* shippingAddress;
/* An optional Map<string,string> of misc properties. 
 */
@property(nonatomic) SWGMeta* meta;

@end
