#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGProductPreviewImage.h"


@protocol SWGProductPreviewRequest
@end

@interface SWGProductPreviewRequest : SWGObject


@property(nonatomic) NSString* sku;

@property(nonatomic) NSString* template;

@property(nonatomic) NSArray<SWGProductPreviewImage>* images;
/* Max height of the resultant image. Defaults to 500px 
 */
@property(nonatomic) NSNumber* maxHeight;
/* Max width of the resultant image. Defaults to 500px 
 */
@property(nonatomic) NSNumber* maxWidth;

@end
