#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGProductOptionList.h"
#import "SWGProductVariant.h"


@protocol SWGProductVariantResponse
@end

@interface SWGProductVariantResponse : SWGObject


@property(nonatomic) NSArray<SWGProductVariant>* productVariants;

@property(nonatomic) NSArray<SWGProductOptionList>* options;

@end
