#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGPreconfiguredItem.h"
#import "SWGPreconfiguredProductImage.h"
#import "SWGProductPriceInfo.h"


@protocol SWGPreconfiguredProduct
@end

@interface SWGPreconfiguredProduct : SWGObject

/* A sku that uniquely identifies the preconfigured product. 
 */
@property(nonatomic) NSString* sku;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _description;

@property(nonatomic) SWGProductPriceInfo* price;
/* The item[s] that constitue the product. 
 */
@property(nonatomic) NSArray<SWGPreconfiguredItem>* items;
/* Product images. Can contain large and small images for web, mobile, etc 
 */
@property(nonatomic) NSArray<SWGPreconfiguredProductImage>* images;

@end
