#import <Foundation/Foundation.h>
#import "SWGProductPreviewRequest.h"
#import "SWGProductPreviewResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGProductpreviewApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGProductpreviewApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGProductpreviewApi*) sharedAPI;
///
///
/// Submit an image (or images) to be rendered into a product preview.
/// Submit an image (or images) to be rendered into a product preview.
///
/// @param productPreviewRequest Request detailing the operation needing completed
/// 
///
/// @return SWGProductPreviewResponse*
-(NSNumber*) pOSTProductpreviewWithProductPreviewRequest: (SWGProductPreviewRequest*) productPreviewRequest
    completionHandler: (void (^)(SWGProductPreviewResponse* output, NSError* error)) handler;



@end
