#import <Foundation/Foundation.h>
#import "SWGPaymentValidationResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGPaymentvalidationApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGPaymentvalidationApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGPaymentvalidationApi*) sharedAPI;
///
///
/// Submit payment validation for PayPal
/// Submit payment validation for PayPal
///
/// @param orderId Order Id returned from orders/POST
/// @param payPalKey The PayPal key returned from the Mobile SDK
/// 
///
/// @return SWGPaymentValidationResponse*
-(NSNumber*) paymentvalidationWithOrderId: (NSString*) orderId
    payPalKey: (NSString*) payPalKey
    completionHandler: (void (^)(SWGPaymentValidationResponse* output, NSError* error)) handler;



@end
