#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGProductOption.h"


@protocol SWGProductVariant
@end

@interface SWGProductVariant : SWGObject


@property(nonatomic) NSString* sku;

@property(nonatomic) NSNumber* maxImages;

@property(nonatomic) NSNumber* hasTemplates;

@property(nonatomic) NSArray<SWGProductOption>* options;

@end
