#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGPreconfiguration.h"


@protocol SWGPreconfiguredItem
@end

@interface SWGPreconfiguredItem : SWGObject

/* The ID of the product this item references. 
 */
@property(nonatomic) NSNumber* productId;
/* The sku of the product variant this item references. 
 */
@property(nonatomic) NSString* productVariantSku;

@property(nonatomic) NSArray<SWGPreconfiguration>* preconfigurations;

@end
