#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGPreconfiguredProduct.h"


@protocol SWGPreconfiguredProductsResponse
@end

@interface SWGPreconfiguredProductsResponse : SWGObject


@property(nonatomic) NSArray<SWGPreconfiguredProduct>* preconfiguredProducts;

@end
