#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProductOptionValueSettings
@end

@interface SWGProductOptionValueSettings : SWGObject


@property(nonatomic) NSString* iconUrl;

@property(nonatomic) NSString* iconType;

@property(nonatomic) NSString* colorRgba;

@end
