#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGProduct.h"


@protocol SWGProductList
@end

@interface SWGProductList : SWGObject


@property(nonatomic) NSArray<SWGProduct>* products;

@end
