#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGProductPreviewImageSpec.h"


@protocol SWGProductPreviewImage
@end

@interface SWGProductPreviewImage : SWGObject


@property(nonatomic) NSString* layerId;

@property(nonatomic) SWGProductPreviewImageSpec* image;

@end
