#import <Foundation/Foundation.h>
#import "SWGProductBuildInfoResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGProducttemplatesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGProducttemplatesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGProducttemplatesApi*) sharedAPI;
///
///
/// Get a list of product templates
/// Get a list of product templates.
///
/// @param sku Productvariant sku.
/// @param languageCode Two-character language code, defaults to \&quot;en\&quot; (english)
/// 
///
/// @return SWGProductBuildInfoResponse*
-(NSNumber*) getProducttemplatesWithSku: (NSString*) sku
    languageCode: (NSString*) languageCode
    completionHandler: (void (^)(SWGProductBuildInfoResponse* output, NSError* error)) handler;



@end
