#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPreconfiguration
@end

@interface SWGPreconfiguration : SWGObject

/* Required only for multi-image items. The ID of the space where an image is to be placed. One can attain the SpaceId via inspecting the template data. 
 */
@property(nonatomic) NSString* spaceId;
/* The url of the image to be placed in the referenced layer. 
 */
@property(nonatomic) NSString* url;

@end
