#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPreconfiguredProductImage
@end

@interface SWGPreconfiguredProductImage : SWGObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* index;

@property(nonatomic) NSString* _id;

@end
