#import <Foundation/Foundation.h>
#import "SWGOrderPriceResult.h"
#import "SWGOrder.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGPriceestimateApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGPriceestimateApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGPriceestimateApi*) sharedAPI;
///
///
/// Get an order price
/// Get the price of an order, including discounts from a coupon.
///
/// @param order Order to potentially be submitted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return SWGOrderPriceResult*
-(NSNumber*) pOSTPriceestimateWithOrder: (SWGOrder*) order
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(SWGOrderPriceResult* output, NSError* error)) handler;



@end
