#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGCategory.h"
#import "SWGProductImage.h"
#import "SWGProductInfo.h"
#import "SWGProductPriceInfo.h"


@protocol SWGProduct
@end

@interface SWGProduct : SWGObject

/* The product type id. Represents a type/class of products. Can later be passed into the productvariant service to get available product variations. 
 */
@property(nonatomic) NSNumber* _id;
/* An id that syncs between printio's staging and live environments. 
 */
@property(nonatomic) NSString* uId;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* shortDescription;
/* Whether or not the item returned is a Product, or ProductVariant. Items with a Sku will not have other product variants 
 */
@property(nonatomic) NSNumber* hasAvailableProductVariants;
/* Whether or not the product has variants with templates. 
 */
@property(nonatomic) NSNumber* hasProductTemplates;
/* A value to sort featured items by. Note that this is null if IsFeatured=false 
 */
@property(nonatomic) NSNumber* featuredIndex;

@property(nonatomic) NSNumber* maxZoom;

@property(nonatomic) SWGProductPriceInfo* retailPrice;
/* Content describing the product. 
 */
@property(nonatomic) NSArray<SWGProductInfo>* info;
/* Product images. Note that this contains large and small images for web, mobile, etc 
 */
@property(nonatomic) NSArray<SWGProductImage>* productImage;

@property(nonatomic) SWGProductPriceInfo* priceInfo;

@property(nonatomic) NSArray<SWGCategory>* categories;

@end
