#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGAddress.h"


@protocol SWGResult
@end

@interface SWGResult : SWGObject


@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NSString* reason;

@property(nonatomic) NSNumber* score;

@property(nonatomic) SWGAddress* proposedAddress;

@end
