#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGSkuQuantityPair.h"


@protocol SWGShippingPricesRequest
@end

@interface SWGShippingPricesRequest : SWGObject


@property(nonatomic) NSString* shipToPostalCode;

@property(nonatomic) NSString* shipToCountry;

@property(nonatomic) NSString* shipToState;

@property(nonatomic) NSString* currencyCode;

@property(nonatomic) NSString* languageCode;

@property(nonatomic) NSArray<SWGSkuQuantityPair>* items;

@end
