#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGItem.h"


@protocol SWGSubmittedOrder
@end

@interface SWGSubmittedOrder : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSArray<SWGItem>* items;

@end
