#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGShipPrice
@end

@interface SWGShipPrice : SWGObject


@property(nonatomic) NSNumber* price;

@property(nonatomic) NSString* currencyCode;

@property(nonatomic) NSString* formattedPrice;

@end
