#import <Foundation/Foundation.h>
#import "SWGShipEstimate.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGShippriceestimateApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGShippriceestimateApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGShippriceestimateApi*) sharedAPI;
///
///
/// Get a baseline ship price for an item
/// Price returned is an estimate which may or may not be realistically attainable.
///
/// @param productId Product ID
/// @param countryCode Country Code it will be shipped to
/// @param currencyCode Currency Code the estimate should be in. Defaults to USD.
/// 
///
/// @return SWGShipEstimate*
-(NSNumber*) getShippriceestimateWithProductId: (NSNumber*) productId
    countryCode: (NSString*) countryCode
    currencyCode: (NSString*) currencyCode
    completionHandler: (void (^)(SWGShipEstimate* output, NSError* error)) handler;



@end
