#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGSkuQuantityPair
@end

@interface SWGSkuQuantityPair : SWGObject


@property(nonatomic) NSString* sKU;

@property(nonatomic) NSNumber* quantity;

@end
