#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMeta.h"
#import "SWGPostSubmittedItem.h"
#import "SWGProductPriceInfo.h"


@protocol SWGSearchSubmittedOrder
@end

@interface SWGSearchSubmittedOrder : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* niceId;
/* Clients can submit an ID they use for the order here. 
 */
@property(nonatomic) NSString* sourceId;

@property(nonatomic) NSArray<SWGPostSubmittedItem>* items;

@property(nonatomic) SWGProductPriceInfo* total;

@property(nonatomic) SWGProductPriceInfo* shippingTotal;

@property(nonatomic) NSString* discountCode;

@property(nonatomic) SWGProductPriceInfo* discountAmount;
/* An optional Map<string,string> of misc properties. 
 */
@property(nonatomic) SWGMeta* meta;

@end
