#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGSearchSubmittedOrder.h"


@protocol SWGSubmittedOrderList
@end

@interface SWGSubmittedOrderList : SWGObject


@property(nonatomic) NSArray<SWGSearchSubmittedOrder>* orders;

@property(nonatomic) NSNumber* totalPages;

@property(nonatomic) NSNumber* page;

@property(nonatomic) NSNumber* hadError;

@end
