#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGUserInfo
@end

@interface SWGUserInfo : SWGObject


@property(nonatomic) NSString* languageCode;

@property(nonatomic) NSString* countryCode;

@property(nonatomic) NSString* countryName;

@property(nonatomic) NSString* currencyName;

@property(nonatomic) NSString* currencyCode;

@property(nonatomic) NSString* currencyFormat;

@end
