#import <Foundation/Foundation.h>
#import "SWGUserInfo.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGUserinfoApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGUserinfoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGUserinfoApi*) sharedAPI;
///
///
/// Get the user's language code and country based upon IP
/// IP-based user info lookup
///
/// @param languageCode Two-character language code, if known at the time.
/// 
///
/// @return SWGUserInfo*
-(NSNumber*) getUserinfoWithLanguageCode: (NSString*) languageCode
    completionHandler: (void (^)(SWGUserInfo* output, NSError* error)) handler;



@end
