#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GAddress
@end

@interface GAddress : GObject


@property(nonatomic) NSString* city;

@property(nonatomic) NSString* countryCode;

@property(nonatomic) NSString* postalCode;

@property(nonatomic) NSString* stateOrProvinceCode;

@property(nonatomic) NSArray* /* NSString */ streetLines;

@end
