#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */






@protocol GCategory
@end

@interface GCategory : GObject



@property(nonatomic) NSNumber* _id;


@property(nonatomic) NSString* name;


@end


