#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GCurrency.h"


@protocol GCountry
@end

@interface GCountry : GObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* code;

@property(nonatomic) NSNumber* isSupported;

@property(nonatomic) NSString* measurementCode;

@property(nonatomic) NSString* flagUrl;

@property(nonatomic) GCurrency* defaultCurrency;

@end
