#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GCountry.h"





@protocol GCountryList
@end

@interface GCountryList : GObject



@property(nonatomic) NSArray<GCountry>* countries;


@end


