#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GCurrency
@end

@interface GCurrency : GObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* format;

@end
