#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GFile
@end

@interface GFile : GObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* url;

@end
