#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GImage.h"


@protocol GFileResult
@end

@interface GFileResult : GObject


@property(nonatomic) NSArray<GImage>* price;

@end
