#import <Foundation/Foundation.h>
#import "GFileResult.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GImagesApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GImagesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GImagesApi*) sharedAPI;
///
///
/// POSTs files to a temporary store
/// POSTs files to a temporary store
///
/// @param images Form/multipart file post
/// 
///
/// @return GFileResult*
-(NSNumber*) postImagesWithImages: (NSURL*) images
    completionHandler: (void (^)(GFileResult* output, NSError* error)) handler;



@end
