#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GImageSizeVm.h"





@protocol GImageValidationVm
@end

@interface GImageValidationVm : GObject



@property(nonatomic) NSString* sku;


@property(nonatomic) NSArray<GImageSizeVm>* images;


@end


