#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GImage
@end

@interface GImage : GObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSNumber* index;

@property(nonatomic) NSString* thumbnailUrl;

@property(nonatomic) NSString* manipCommand;

@property(nonatomic) NSString* spaceId;

@end
