#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GValidationFailure.h"


@protocol GImageValidatorResult
@end

@interface GImageValidatorResult : GObject


@property(nonatomic) NSNumber* hadError;

@property(nonatomic) NSArray<GValidationFailure>* issues;

@end
