#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */






@protocol GItem
@end

@interface GItem : GObject



@property(nonatomic) NSNumber* quantity;


@property(nonatomic) NSString* sku;


@property(nonatomic) NSString* status;


@property(nonatomic) NSString* product;


@end


