#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */






@protocol GKeyValuePair
@end

@interface GKeyValuePair : GObject



@property(nonatomic) NSString* key;


@property(nonatomic) NSString* value;


@end


