#import <Foundation/Foundation.h>
#import "GLanguageDictionary.h"

#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */


@interface GLanguagesApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GLanguagesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GLanguagesApi*) sharedAPI;

///
///
/// Get text in a specified language
/// Get text in a specified language
///
/// @param languageCode Two-character language code, like \&quot;en\&quot; (english)
/// @param key A string used to query the language dictionary for specific values within a category.
/// 
///
/// @return GLanguageDictionary*
-(NSNumber*) getLanguageTextWithLanguageCode: (NSString*) languageCode
    key: (NSString*) key
    completionHandler: (void (^)(GLanguageDictionary* output, NSError* error)) handler;





@end
