#import <Foundation/Foundation.h>
#import "GOrderStatusUpdateResult.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GOrderstatusApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GOrderstatusApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GOrderstatusApi*) sharedAPI;
///
///
/// Update an order status
/// Update status of each order item.
///
/// @param partnerBillingKey Partner billing key
/// @param _id Order Id
/// @param orderStatusName Order status name for update
/// 
///
/// @return GOrderStatusUpdateResult*
-(NSNumber*) pOSTOrderstatusWithPartnerBillingKey: (NSString*) partnerBillingKey
    _id: (NSString*) _id
    orderStatusName: (NSString*) orderStatusName
    completionHandler: (void (^)(GOrderStatusUpdateResult* output, NSError* error)) handler;



@end
