#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GOrderItem.h"
#import "GPayment.h"
#import "GShipToAddress.h"


@protocol GOrder
@end

@interface GOrder : GObject


@property(nonatomic) GShipToAddress* shipToAddress;

@property(nonatomic) NSArray<GOrderItem>* items;

@property(nonatomic) GPayment* payment;

@property(nonatomic) NSString* couponCode;

@end
