#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GPriceInfo.h"





@protocol GOrderPriceResult
@end

@interface GOrderPriceResult : GObject



@property(nonatomic) GPriceInfo* items;


@property(nonatomic) GPriceInfo* shipping;


@property(nonatomic) GPriceInfo* tax;


@property(nonatomic) GPriceInfo* couponCode;


@property(nonatomic) NSString* couponType;


@property(nonatomic) NSString* couponUsed;


@property(nonatomic) NSNumber* hadCouponApply;


@property(nonatomic) NSNumber* dollarsOff;


@property(nonatomic) NSNumber* percentOff;


@property(nonatomic) NSNumber* hadError;


@end


