#import <Foundation/Foundation.h>
#import "GPostSubmittedOrder.h"
#import "GOrderResult.h"
#import "GPostOrder.h"

#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */


@interface GOrdersApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GOrdersApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GOrdersApi*) sharedAPI;

///
///
/// Get an order
/// Gets basic information about an order.
///
/// @param _id Order Id
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// @param languageCode Resultant info language. Defaults to &#39;en&#39;.
/// 
///
/// @return GPostSubmittedOrder*
-(NSNumber*) gETOrdersWithId: (NSString*) _id
    version: (NSNumber*) version
    source: (NSString*) source
    languageCode: (NSString*) languageCode
    completionHandler: (void (^)(GPostSubmittedOrder* output, NSError* error)) handler;



///
///
/// Submit an order
/// Places an order into the system. An order can be submitted as PrePayment (in order to temporarily place an order and get an ID for Paypal) using the IsPreSubmit flag.
///
/// @param order Order to be submitted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return GOrderResult*
-(NSNumber*) pOSTOrdersWithOrder: (GPostOrder*) order
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(GOrderResult* output, NSError* error)) handler;





@end
