#import <Foundation/Foundation.h>
#import "GPreconfiguredProductInsert.h"
#import "GPreconfiguredProductsInsertResponse.h"
#import "GPreconfiguredProductsResponse.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GPreconfiguredproductsApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GPreconfiguredproductsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GPreconfiguredproductsApi*) sharedAPI;
///
///
/// Insert a preconfigured product
/// Insert a preconfigured product into your recipe.
///
/// @param preconfiguredProductInsert The product to be inserted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return GPreconfiguredProductsInsertResponse*
-(NSNumber*) createPreconfiguredproductsWithPreconfiguredProductInsert: (GPreconfiguredProductInsert*) preconfiguredProductInsert
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(GPreconfiguredProductsInsertResponse* output, NSError* error)) handler;


///
///
/// Delete a preconfigured product
/// Delete a preconfigured product from your recipe.
///
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// @param sku The preconfigured product&#39;s sku.
/// 
///
/// @return GPreconfiguredProductsInsertResponse*
-(NSNumber*) deletePreconfiguredproductsWithVersion: (NSNumber*) version
    source: (NSString*) source
    sku: (NSString*) sku
    completionHandler: (void (^)(GPreconfiguredProductsInsertResponse* output, NSError* error)) handler;


///
///
/// Get a list of your preconfigured products
/// Get a list of your preconfigured products. The products returned are entirely specific to your recipe.
///
/// @param countryCode The country code where it would be shipped to. For example, &#39;US&#39; or &#39;CA&#39;
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// @param languageCode Two-character language code, defaults to \&quot;en\&quot; (english)
/// @param currencyCode Three character currency code, defaults to \&quot;USD\&quot; (united states dollar)
/// 
///
/// @return GPreconfiguredProductsResponse*
-(NSNumber*) getPreconfiguredproductsWithCountryCode: (NSString*) countryCode
    version: (NSNumber*) version
    source: (NSString*) source
    languageCode: (NSString*) languageCode
    currencyCode: (NSString*) currencyCode
    completionHandler: (void (^)(GPreconfiguredProductsResponse* output, NSError* error)) handler;


///
///
/// Update a preconfigured product
/// Update a preconfigured product into your recipe.
///
/// @param preconfiguredProductInsert The product to be inserted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return GPreconfiguredProductsInsertResponse*
-(NSNumber*) updatePreconfiguredproductsWithPreconfiguredProductInsert: (GPreconfiguredProductInsert*) preconfiguredProductInsert
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(GPreconfiguredProductsInsertResponse* output, NSError* error)) handler;



@end
