#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GPreconfiguredItem.h"
#import "GPreconfiguredProductImage.h"
#import "GProductPriceInfo.h"





@protocol GPreconfiguredProduct
@end

@interface GPreconfiguredProduct : GObject


/* A sku that uniquely identifies the preconfigured product. 
 */
@property(nonatomic) NSString* sku;


@property(nonatomic) NSString* name;


@property(nonatomic) NSString* _description;


@property(nonatomic) GProductPriceInfo* price;

/* The item[s] that constitue the product. 
 */
@property(nonatomic) NSArray<GPreconfiguredItem>* items;

/* Product images. Can contain large and small images for web, mobile, etc 
 */
@property(nonatomic) NSArray<GPreconfiguredProductImage>* images;


@end


