#import <Foundation/Foundation.h>
#import "GOrderPriceResult.h"
#import "GOrder.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GPriceestimateApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GPriceestimateApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GPriceestimateApi*) sharedAPI;
///
///
/// Get an order price
/// Get the price of an order, including discounts from a coupon.
///
/// @param order Order to potentially be submitted
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api
/// 
///
/// @return GOrderPriceResult*
-(NSNumber*) pOSTPriceestimateWithOrder: (GOrder*) order
    version: (NSNumber*) version
    source: (NSString*) source
    completionHandler: (void (^)(GOrderPriceResult* output, NSError* error)) handler;



@end
