#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GProductPreviewResponse
@end

@interface GProductPreviewResponse : GObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSNumber* hadError;

@property(nonatomic) NSString* errorMessage;

@end
