#import <Foundation/Foundation.h>
#import "GProductPreviewResponse.h"
#import "GProductPreviewRequest.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GProductpreviewApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GProductpreviewApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GProductpreviewApi*) sharedAPI;
///
///
/// Submit an image (or images) to be rendered into a product preview.
/// Submit an image (or images) to be rendered into a product preview.
///
/// @param productPreviewRequest Request detailing the operation needing completed
/// 
///
/// @return GProductPreviewResponse*
-(NSNumber*) pOSTProductpreviewWithProductPreviewRequest: (GProductPreviewRequest*) productPreviewRequest
    completionHandler: (void (^)(GProductPreviewResponse* output, NSError* error)) handler;



@end
