#import <Foundation/Foundation.h>
#import "GProductVariantResponse.h"

#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */


@interface GProductvariantsApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GProductvariantsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GProductvariantsApi*) sharedAPI;

///
///
/// Get a list of available product variations. Includes pricing information
/// Get a list of all available product variations, or if one passes in a specific product type id (productId), gets a list of available variations of a recipe product.
///
/// @param countryCode The country code the order would be shipped to. For example, &#39;US&#39; or &#39;FR&#39;
/// @param productId Recipe product ID, such as those returned from the /products service
/// @param version Version of the api being used
/// @param source Description of the source-- ios, android, api, widget
/// @param partnerBillingKey Partner billing key
/// @param all Whether or not to return all available printio products, or just ones in your recipe. Pass &#39;true&#39; or &#39;false&#39;.
/// @param languageCode Two-character language code, defaults to \&quot;en\&quot; (english)
/// @param currencyCode Three character currency code, defaults to \&quot;USD\&quot; (united states dollar)
/// 
///
/// @return GProductVariantResponse*
-(NSNumber*) getProductvariantsWithCountryCode: (NSString*) countryCode
    productId: (NSString*) productId
    version: (NSNumber*) version
    source: (NSString*) source
    partnerBillingKey: (NSString*) partnerBillingKey
    all: (NSString*) all
    languageCode: (NSString*) languageCode
    currencyCode: (NSString*) currencyCode
    completionHandler: (void (^)(GProductVariantResponse* output, NSError* error)) handler;





@end
