#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GProductPreviewImage.h"





@protocol GProductPreviewRequest
@end

@interface GProductPreviewRequest : GObject



@property(nonatomic) NSString* sku;


@property(nonatomic) NSString* template;


@property(nonatomic) NSArray<GProductPreviewImage>* images;

/* Max height of the resultant image. Defaults to 500px 
 */
@property(nonatomic) NSNumber* maxHeight;

/* Max width of the resultant image. Defaults to 500px 
 */
@property(nonatomic) NSNumber* maxWidth;


@end


