#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GProductOptionList.h"
#import "GProductVariant.h"





@protocol GProductVariantResponse
@end

@interface GProductVariantResponse : GObject



@property(nonatomic) NSArray<GProductVariant>* productVariants;


@property(nonatomic) NSArray<GProductOptionList>* options;


@end


