#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GProductOption.h"
#import "GProductPriceInfo.h"


@protocol GProductVariant
@end

@interface GProductVariant : GObject


@property(nonatomic) NSString* sku;

@property(nonatomic) NSNumber* maxImages;

@property(nonatomic) NSNumber* hasTemplates;

@property(nonatomic) NSArray<GProductOption>* options;

@property(nonatomic) GProductPriceInfo* priceInfo;

@property(nonatomic) GProductPriceInfo* partnerPriceInfo;

@end
