#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GProductPreviewImageSpec.h"


@protocol GProductPreviewImage
@end

@interface GProductPreviewImage : GObject


@property(nonatomic) NSString* layerId;

@property(nonatomic) GProductPreviewImageSpec* image;

@end
