#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GProductImage
@end

@interface GProductImage : GObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* index;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSArray* /* NSString */ imageTypes;

@end
