#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */






@protocol GProductOption
@end

@interface GProductOption : GObject



@property(nonatomic) NSString* optionId;


@property(nonatomic) NSString* valueId;


@property(nonatomic) NSString* name;


@property(nonatomic) NSString* value;


@property(nonatomic) NSString* imageUrl;


@property(nonatomic) NSString* imageType;


@property(nonatomic) NSString* rgbaColor;


@property(nonatomic) NSString* cmValue;


@property(nonatomic) NSString* sortValue;


@end


