#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GProductBuildInfoSpace.h"


@protocol GProductBuildOption
@end

@interface GProductBuildOption : GObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* imageUrl;

@property(nonatomic) NSNumber* isDefault;

@property(nonatomic) NSString* category;

@property(nonatomic) NSNumber* isPartnerSpecific;

@property(nonatomic) NSArray<GProductBuildInfoSpace>* spaces;

@end
