#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */






@protocol GProductBuildInfo
@end

@interface GProductBuildInfo : GObject



@property(nonatomic) NSString* _id;


@property(nonatomic) NSString* _description;


@property(nonatomic) NSString* type;


@property(nonatomic) NSNumber* zIndex;


@property(nonatomic) NSNumber* x1;


@property(nonatomic) NSNumber* x2;


@property(nonatomic) NSNumber* y1;


@property(nonatomic) NSNumber* y2;


@property(nonatomic) NSString* color;


@property(nonatomic) NSString* backgroundImageUrl;


@property(nonatomic) NSString* overlayImageUrl;


@property(nonatomic) NSString* fontName;


@property(nonatomic) NSString* fontSize;


@property(nonatomic) NSString* fontHAlignment;


@property(nonatomic) NSString* fontVAlighment;


@property(nonatomic) NSString* defaultText;


@end


