#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GProductPreviewImageSpec
@end

@interface GProductPreviewImageSpec : GObject


@property(nonatomic) NSString* url;

@property(nonatomic) NSNumber* x1;

@property(nonatomic) NSNumber* x2;

@property(nonatomic) NSNumber* y1;

@property(nonatomic) NSNumber* y2;

@end
