#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GAddress.h"





@protocol GResult
@end

@interface GResult : GObject



@property(nonatomic) NSNumber* isValid;


@property(nonatomic) NSString* reason;


@property(nonatomic) NSNumber* score;


@property(nonatomic) GAddress* proposedAddress;


@end


