#import <Foundation/Foundation.h>
#import "GShipEstimate.h"

#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */


@interface GShippriceestimateApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GShippriceestimateApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GShippriceestimateApi*) sharedAPI;

///
///
/// Get a baseline ship price for an item
/// Price returned is an estimate which may or may not be realistically attainable.
///
/// @param productId Product ID
/// @param countryCode Country Code it will be shipped to
/// @param currencyCode Currency Code the estimate should be in. Defaults to USD.
/// 
///
/// @return GShipEstimate*
-(NSNumber*) getShippriceestimateWithProductId: (NSNumber*) productId
    countryCode: (NSString*) countryCode
    currencyCode: (NSString*) currencyCode
    completionHandler: (void (^)(GShipEstimate* output, NSError* error)) handler;





@end
