#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GShipment
@end

@interface GShipment : GObject


@property(nonatomic) NSString* trackingNumber;

@property(nonatomic) NSString* trackingUrl;

@property(nonatomic) NSString* shipCarrierName;

@end
