#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GShipPrice.h"


@protocol GShipOption
@end

@interface GShipOption : GObject

/* The ID that can be passed into the /orders POST endpoing as ShipCarrierMethodId to specify an item's shipping method. 
 */
@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* methodType;

@property(nonatomic) NSNumber* methodId;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* carrierName;

@property(nonatomic) NSString* carrierLogoUrl;

@property(nonatomic) GShipPrice* price;

@property(nonatomic) GShipPrice* partnerPrice;

@property(nonatomic) NSNumber* estBusinessDaysTilDelivery;

@end
