#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GShipPrice.h"


@protocol GShipEstimate
@end

@interface GShipEstimate : GObject


@property(nonatomic) GShipPrice* minPrice;

@property(nonatomic) GShipPrice* maxPrice;

@property(nonatomic) NSString* vendorCountryCode;

@property(nonatomic) NSNumber* canShipExpedited;

@property(nonatomic) NSNumber* estShipDays;

@end
