#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GShipOption.h"


@protocol GShipItem
@end

@interface GShipItem : GObject


@property(nonatomic) NSArray* /* NSString */ sKUs;

@property(nonatomic) NSArray<GShipOption>* shipOptions;

@end
