#import <Foundation/Foundation.h>
#import "GShippingPricesResult.h"
#import "GShippingPricesRequest.h"

#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */


@interface GShippingpricesApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GShippingpricesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GShippingpricesApi*) sharedAPI;

///
///
/// Get a list of shipping options and prices for items
/// Get a list of shipping options and prices for items.
///
/// @param shippingPricesRequest DTO with required information
/// @param partnerBillingKey Partner billing key
/// 
///
/// @return GShippingPricesResult*
-(NSNumber*) pOSTShippingpricesWithShippingPricesRequest: (GShippingPricesRequest*) shippingPricesRequest
    partnerBillingKey: (NSString*) partnerBillingKey
    completionHandler: (void (^)(GShippingPricesResult* output, NSError* error)) handler;





@end
