#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GSkuQuantityPair
@end

@interface GSkuQuantityPair : GObject


@property(nonatomic) NSString* sKU;

@property(nonatomic) NSNumber* quantity;

@end
