#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "GItem.h"


@protocol GSubmittedOrder
@end

@interface GSubmittedOrder : GObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSArray<GItem>* items;

@end
