#import <Foundation/Foundation.h>
#import "GUserInfo.h"
#import "GObject.h"
#import "GApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface GUserinfoApi: NSObject

@property(nonatomic, assign)GApiClient *apiClient;

-(instancetype) initWithApiClient:(GApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(GUserinfoApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(GUserinfoApi*) sharedAPI;
///
///
/// Get the user's language code and country based upon IP
/// IP-based user info lookup
///
/// @param languageCode Two-character language code, if known at the time.
/// 
///
/// @return GUserInfo*
-(NSNumber*) getUserinfoWithLanguageCode: (NSString*) languageCode
    completionHandler: (void (^)(GUserInfo* output, NSError* error)) handler;



@end
