#import <Foundation/Foundation.h>
#import "GObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol GValidationFailure
@end

@interface GValidationFailure : GObject


@property(nonatomic) NSString* propertyName;

@property(nonatomic) NSString* errorMessage;

@property(nonatomic) NSString* attemptedValue;

@end
